# Generated by Django 3.2.5 on 2022-06-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login_at', models.DateField(auto_now_add=True)),
                ('last_apply_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
